const BlogTypes = {
  ADD_POST_HIDDEN: "ADD_POST_HIDDEN",
  ADD_NEW_POST_START: "ADD_NEW_POST_START",
  ADD_NEW_POST_SUCCESS: "ADD_NEW_POST_SUCCESS",
  ADD_NEW_POST_FAILURE: "ADD_NEW_POST_FAILURE",
  EDIT_POST_START: "EDIT_POST_START",
  EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
  EDIT_POST_FAILURE: "EDIT_POST_FAILURE",
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};
export default BlogTypes;
